name: sliver_snap
description: Allows you to use powerful snapping slivers with expanded and collapsed bars.
version: 1.2.0
repository: https://github.com/A-Fawzyy/sliver-snap
issue_tracker: https://github.com/A-Fawzyy/sliver-snap/issues



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^5.7.6
  lint: ^2.3.0

screenshots:
  - description: 'Preview of the basic SliverSnap usage.'
    path: previews/basic_preview.webp


flutter:
